### ISSUE TITLE
Miss-formatting LESS file

### ISSUE THREAD

**Issue by edoher** [Hirse/brackets-beautify#7]
Hi, the plugin so far works great. Today I found an issue that took me a lot of effort to understand.

``` less
#main > header.big-menu nav ul.level-3 > li > ul li div a:hover {
    &:extend(#main > header.big-menu nav ul li > a: hover);
}
```

Beautify added a random space in that piece of code, within a LESS file of over 1000 lines, making it impossible for me to compile it and even harder for me to understand what was wrong.

For some reason, Beautify added a space in "a:hover", making it be "a: hover", therefore rendering it invalid.

Please check that error, because probably I'm not the only one who had a hard time with it.

Thanks!

**Comment by Hirse** [comment]
I am sorry you are having issues with less formatting.
Unfortunately this is caused by issues in the underlying [library](https://github.com/beautify-web/js-beautify).
There are some issues about less formatting, the one that comes closest to your described behavior is probably https://github.com/beautify-web/js-beautify/issues/631.
Please add a comment there or open another issue and feel free to mention me.

Regarding this extension, I can only advise you to not use it for less files at the moment and deactivate _Beautify-on-Save_ for those by adding this to the `brackets.json`:

``` json
{
    "language": {
        "less": {
            "hirse.beautify.onSave": false
        }
    }
}
```

**Comment by edoher** [comment]
Thanks, that's working!
