### ISSUE TITLE
Inconsistency in indentation

### ISSUE THREAD

**Issue by edoher** [Hirse/brackets-beautify#8]
Hi,
The plugin doesn't work consistently, leading to have this differences in the same HTML file.

``` html
                                                    <div class="button right">
                                                        <a href="cont_1_tech_specs.php">
                                                                            Find technical specifications
                                                                            <i class="velux-icon icon-chevron-right-white"></i>
                                                                        </a>
                                                    </div>
```

``` html
                                                <li>
                                                    <a href="#">Balcony and terrace</a>
                                                </li>
```

``` html
<li><a href="#">Domestic buildings</a></li>
```

**Comment by Hirse** [comment]
How do you format the file?
Do you run beautify on the whole file or only on the selected snippits?
In the latter case, there can be issues due to missing context in the formatting.

In any case, please test the beautification with the library directly here: http://jsbeautifier.org/
I have a feeling this is (also) an issue with the library rather than this extension.

**Comment by edoher** [comment]
I do it both by pressing Ctrl + Alt + B or simply by setting "Beautify on save" to checked.
